# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/ (optional)
url: "http://www.amandalee.me" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Amanda Lee Anderson # Your name will go here
  description: "I build stuff. Designer, developer, writer, musician." # used by search engines

  # Header and footer text
  header_text: >
     <h1>Amanda Lee Anderson</h1>
     <p>I build stuff. Designer, developer, writer, musician.</p>
  header_text_feature_image:
  footer_text: 
    '&copy; 2016 ALA. <a href="mailto: amandalee.anderson@gmail.com">Get in touch</a>'

  # Icons
  rss: false
  email_address: amandalee.anderson@gmail.com
  github: amandaleee 
  pinterest:
  reddit:
  soundcloud:
  steam:
  tumblr:
  twitter: amandalee
  youtube:

  # Scripts
  google_analytics: UA-2700135-25
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Montserrat:400,700|Questrial|Rokkitt:400,700"

# PAGINATION
paginate: 100
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# BUILD SETTINGS
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
